// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prime.proto

package primepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimeMessage struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeMessage) Reset()         { *m = PrimeMessage{} }
func (m *PrimeMessage) String() string { return proto.CompactTextString(m) }
func (*PrimeMessage) ProtoMessage()    {}
func (*PrimeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f062ee0f679da716, []int{0}
}

func (m *PrimeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeMessage.Unmarshal(m, b)
}
func (m *PrimeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeMessage.Marshal(b, m, deterministic)
}
func (m *PrimeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeMessage.Merge(m, src)
}
func (m *PrimeMessage) XXX_Size() int {
	return xxx_messageInfo_PrimeMessage.Size(m)
}
func (m *PrimeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeMessage proto.InternalMessageInfo

func (m *PrimeMessage) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeRequest struct {
	Message              *PrimeMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PrimeRequest) Reset()         { *m = PrimeRequest{} }
func (m *PrimeRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeRequest) ProtoMessage()    {}
func (*PrimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f062ee0f679da716, []int{1}
}

func (m *PrimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeRequest.Unmarshal(m, b)
}
func (m *PrimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeRequest.Marshal(b, m, deterministic)
}
func (m *PrimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeRequest.Merge(m, src)
}
func (m *PrimeRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeRequest.Size(m)
}
func (m *PrimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeRequest proto.InternalMessageInfo

func (m *PrimeRequest) GetMessage() *PrimeMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type PrimeResponse struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeResponse) Reset()         { *m = PrimeResponse{} }
func (m *PrimeResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeResponse) ProtoMessage()    {}
func (*PrimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f062ee0f679da716, []int{2}
}

func (m *PrimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeResponse.Unmarshal(m, b)
}
func (m *PrimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeResponse.Marshal(b, m, deterministic)
}
func (m *PrimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeResponse.Merge(m, src)
}
func (m *PrimeResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeResponse.Size(m)
}
func (m *PrimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeResponse proto.InternalMessageInfo

func (m *PrimeResponse) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*PrimeMessage)(nil), "prime.PrimeMessage")
	proto.RegisterType((*PrimeRequest)(nil), "prime.PrimeRequest")
	proto.RegisterType((*PrimeResponse)(nil), "prime.PrimeResponse")
}

func init() { proto.RegisterFile("prime.proto", fileDescriptor_f062ee0f679da716) }

var fileDescriptor_f062ee0f679da716 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0xcc,
	0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xd4, 0xb8, 0x78, 0x02,
	0x40, 0x0c, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x31, 0x2e, 0xb6, 0xbc, 0xd2, 0xdc,
	0xa4, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0xc9, 0x16, 0xaa, 0x2e,
	0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x97, 0x8b, 0x3d, 0x17, 0xa2, 0x05, 0xac, 0x90,
	0xdb, 0x48, 0x58, 0x0f, 0x62, 0x3a, 0xb2, 0x69, 0x41, 0x30, 0x35, 0x4a, 0xea, 0x5c, 0xbc, 0x50,
	0xed, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0x38, 0xed, 0x31, 0xf2, 0x82, 0xda, 0x13, 0x9c, 0x5a, 0x54,
	0x96, 0x99, 0x9c, 0x2a, 0x64, 0xc5, 0xc5, 0xe9, 0x96, 0x98, 0x5c, 0x92, 0x5f, 0x94, 0x59, 0x95,
	0x2a, 0x84, 0x62, 0x07, 0xd4, 0x25, 0x52, 0x22, 0xa8, 0x82, 0x10, 0xf3, 0x95, 0x18, 0x0c, 0x18,
	0x9d, 0x38, 0xa3, 0xd8, 0xc1, 0x52, 0x05, 0x49, 0x49, 0x6c, 0x60, 0x4f, 0x1b, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x24, 0x98, 0x6d, 0x03, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrimeServiceClient is the client API for PrimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeServiceClient interface {
	Factorize(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (PrimeService_FactorizeClient, error)
}

type primeServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrimeServiceClient(cc *grpc.ClientConn) PrimeServiceClient {
	return &primeServiceClient{cc}
}

func (c *primeServiceClient) Factorize(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (PrimeService_FactorizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeService_serviceDesc.Streams[0], "/prime.PrimeService/Factorize", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeServiceFactorizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeService_FactorizeClient interface {
	Recv() (*PrimeResponse, error)
	grpc.ClientStream
}

type primeServiceFactorizeClient struct {
	grpc.ClientStream
}

func (x *primeServiceFactorizeClient) Recv() (*PrimeResponse, error) {
	m := new(PrimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeServiceServer is the server API for PrimeService service.
type PrimeServiceServer interface {
	Factorize(*PrimeRequest, PrimeService_FactorizeServer) error
}

// UnimplementedPrimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeServiceServer struct {
}

func (*UnimplementedPrimeServiceServer) Factorize(req *PrimeRequest, srv PrimeService_FactorizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Factorize not implemented")
}

func RegisterPrimeServiceServer(s *grpc.Server, srv PrimeServiceServer) {
	s.RegisterService(&_PrimeService_serviceDesc, srv)
}

func _PrimeService_Factorize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeServiceServer).Factorize(m, &primeServiceFactorizeServer{stream})
}

type PrimeService_FactorizeServer interface {
	Send(*PrimeResponse) error
	grpc.ServerStream
}

type primeServiceFactorizeServer struct {
	grpc.ServerStream
}

func (x *primeServiceFactorizeServer) Send(m *PrimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeService",
	HandlerType: (*PrimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Factorize",
			Handler:       _PrimeService_Factorize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime.proto",
}
